version: "3"
services:
  grafana:
    image: grafana/grafana:8.0.5
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    env_file:
      ./docker/env/.telegram.env
    environment:
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
    volumes:
      - ./docker/config/grafana/provisioning:/etc/grafana/provisioning
  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081
    environment:
      ENABLE_METRICS: 'true'
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - lido_terra
  lido_terra:
    build: .