version: "3"
services:
  grafana:
    image: grafana/grafana:8.0.5
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./config/grafana/dashboards:/etc/grafana/provisioning/dashboards
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      # - '--storage.tsdb.path=/prometheus'
      # - '--web.console.libraries=/etc/prometheus/console_libraries'
      # - '--web.console.templates=/etc/prometheus/consoles'
      # - '--web.enable-lifecycle'
    depends_on:
      - lido_terra
  lido_terra:
    build: .