version: "3"
services:
  grafana:
    image: grafana/grafana:8.0.5
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    depends_on:
      - prometheus
    env_file:
      ./docker/env/.telegram.env
    environment:
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
    volumes:
      - ./docker/config/grafana/provisioning:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana
  renderer:
    image: grafana/grafana-image-renderer:latest
    environment:
      ENABLE_METRICS: 'true'
  prometheus:
    image: prom/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    depends_on:
      - lido_terra
  lido_terra:
    build: .
    env_file:
      ./docker/env/.lido_terra.env
    logging:
      driver: "json-file"
      options:
        tag: "lido_terra"
  loki:
    image: grafana/loki:2.3.0
    volumes:
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml


  promtail:
    image: grafana/promtail:2.3.0
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - promtail-data:/var/lib/promtail/positions
      - ./docker/config/promtail/promtail.yml:/etc/promtail/promtail.yml
    command: -config.file=/etc/promtail/promtail.yml


volumes:
  prometheus-data:
  grafana-storage:
  promtail-data:
  loki-data:
