server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: containers
    static_configs:
    - targets:
      - localhost
      labels:
        job: containerlogs
        __path__: /var/lib/docker/containers/*/*log # for linux only
    pipeline_stages:
    - match:
        selector: '{job="containerlogs"}'
        stages:
        - json:
            expressions:
              service_name: attrs.tag
        - regex:
            expression: level=(?P<log_level>([^\ ]+))
        - labels:
            service_name:
            log_level:
    - match:
        selector: '{job="containerlogs", service_name=""}'
        action: drop